# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Modelling Ecology & Evolution Zurich"
email: "meez2019@ieu.uzh.ch"
description: "MEEZ is a modelling seminar for junior researchers in
Ecology & Evolutionary Biology"
baseurl: ""
url: "https://meez2019.github.io"
#permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
twitterAccount: "@meez2019"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/e/1FAIpQLScwdz8PhE8FDZOlGek8IFIHnLl9tR6mnaEdHQx_vT4yBSztuw/viewform"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLScwdz8PhE8FDZOlGek8IFIHnLl9tR6mnaEdHQx_vT4yBSztuw/viewform", text:  "Become a speaker / Present a poster"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLScwdz8PhE8FDZOlGek8IFIHnLl9tR6mnaEdHQx_vT4yBSztuw/viewform", text:  "Become a speaker / Present a poster"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Modelling Ecology & Evolution <typeout> 2019"
eventDate: "27-28 June 2019"
typeoutTextValues: '"", "Zurich"'
typeoutFallback: "Zurich"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLScwdz8PhE8FDZOlGek8IFIHnLl9tR6mnaEdHQx_vT4yBSztuw/viewform", text: "Become a speaker / Present a poster"}
 
# About Block
aboutTitle: "About MEEZ conference"
aboutBlock:
 - {title: "A modelling seminar for junior researchers in
Ecology & Evolutionary Biology
",  text: "bezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb stbezfzefzefz efezfzefze fzefzefzefzefze njty hgqezfnsrtyghb st" }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Keynote speakers"
rockstarSpeakersButtonText: "See all speakers"
 

# Latest News Block
latestNewsTitle: "Latest news"

 # statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "", info: "attendees"}
 - {count: "20", specialCharacter: "", info: "presentations"}
 - {count: "20", specialCharacter: "", info: "posters"}
 - {count: "4", specialCharacter: "", info: "keynote speakers", detail: "from USA, France and Switzerland"}

 
 

 
 
# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "http://bg.uzh.ch"
eventStreetAddress: "Zollikerstrasse 107"
eventAddressLocality: "Zürich"
#eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "8008"
eventAddressCountry: "Switzerland"
eventStartTime: "2019-06-27T08:30"
eventDoorTime: "08:30"
eventEndTime: "2019-06-8T20:00"
eventPlaceCoordinates: "47.358114, 8.561900"
mapCenterCoordinates: "47.358114, 8.561900"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Botanical garden"
venueFeatures: ["2 rooms", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "meez2019"
twitterFeed: "http://XXXX"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"


# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
 
 
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.ieu.uzh.ch/en.html", text: "Department of Evolutionary Biology and Environmental Studies"}

   
  title: "Contacts"
  links:
   - {link: "meez2019@ieu.uzh.ch", text: "meez2019@ieu.uzh.ch"}

   

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."


# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Travelling to Botanical Garden Zürich"
directionDetailsCards:
 - {title: "From Zürich main station or airport", information: 'When arriving at the airport, first take the train to Zürich main station. There are many different trains running this connection. <br> <b>From the main station</b> take bus 31 in the direction of Kienastenwies and get off at Freiestrasse, from there take bus 33E in the direction of Tiefenbrunnen and get off at Botanische Garten, a 8 min walk will take you to the entrance of the building. '}
 - {title: "From university locations within Zürich", information: '<b>From University of Zürich - Irchel Campus:</b> Take tram 7 in the direction of Wollishofen and get off at Central, from there take tram 4 in the direction of Bahnhof Tiefenbrunnen and get of at Fröhlichstrasse and walk for 7 minutes. <br> <b> From ETH/zentrum:</b> Walk to Neumarkt busstation and take bus number 31 in the direction of Kienastenwies, get off at Freiestrasse and take bus 33E in the direction of Bahnhof Tiefenbrunnen, get off at Botanischer Garten and walk for 8 minutes.'}
 - {title: "Finding the room", information: 'How to find the room'}
directionDetailsWideCards:
 -
  title: "Additional information for travelling and staying in Zürich"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

